#!/usr/bin/env sh

# Change to the project directory where node_modules and package.json are located
cd asce1062

# Run lint-staged for file-specific linting and formatting
npx lint-staged

# Run tests after linting. Fail the commit if any test fails
STAGED_SOURCE=$(git diff --cached --name-only | grep -E '\.(ts|js|mjs|astro)$')

if [ -n "$STAGED_SOURCE" ]; then
  npm test
fi
